title: "Klim's blog"
author: "Klim Troyan"
description: "A blog about Science, AI and more" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# name: Klim Troyan
avatar: images/DALL-E_2022-08-21-22_16_48.png
logo: images/DALL-E_2022-08-21_22-12-39.png # filename of a logo image that has been placed into your images directory

layout: post
# excerpt: "What's interesting here"
# tags: [introduction, beginner, GitHub pages, test]
# comments: false
category: blog


# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "klim.troyan@gmail.com"
# twitter_username: "twitteruser"
github_username: "ktroyan"
linkedin_username: "klim-troyan"
#facebook_username: username
#instagram_username: username
#youtube_username: username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
